version: '3.3'

services:
  application:
    user: node
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 12
    command: sleep infinity
    env_file: .env.development
    ports:
      - 3000:3000
    volumes:
      - ..:/workspace:cached
    links:
      - database

  database:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: .env.development
